// Builds ONE plain .sql file you can paste into the Supabase SQL editor.
//
// supabase/schema.sql uses psql's \ir include directive, which only psql
// understands — pasting it into the dashboard fails, and installing psql just
// to run a migration is a silly requirement. This inlines every migration in
// order and strips the psql-only lines.
//
//   node supabase/build_sql.mjs
//   -> supabase/FULL_SCHEMA.sql   (open it, copy all, paste, Run)

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const entry = readFileSync(join(here, "schema.sql"), "utf8");

// Order comes from schema.sql itself, so this cannot drift out of sync.
const files = [...entry.matchAll(/^\\ir\s+(\S+)/gm)].map((m) => m[1]);
if (!files.length) throw new Error("no \\ir includes found in schema.sql");

const out = [
  "-- Meowave — full schema, generated by supabase/build_sql.mjs",
  "-- Paste the whole file into the Supabase SQL editor and press Run.",
  "-- Safe to run repeatedly: every statement is idempotent.",
  "",
];

for (const f of files) {
  const body = readFileSync(join(here, f), "utf8")
    // \echo is a psql client command and is a syntax error server-side.
    .split("\n")
    .filter((l) => !/^\s*\\/.test(l))
    .join("\n");
  out.push(`-- ======================================================`);
  out.push(`-- ${f}`);
  out.push(`-- ======================================================`);
  out.push(body, "");
}

const sql = out.join("\n");
const target = join(here, "FULL_SCHEMA.sql");
writeFileSync(target, sql);

console.log(`Wrote ${target}`);
console.log(`${files.length} migrations, ${(sql.length / 1024).toFixed(0)} KB`);
console.log("\nNext:");
console.log("  1. Open the file and copy everything");
console.log("  2. Supabase dashboard -> SQL Editor -> New query");
console.log("  3. Paste, press Run");
