-- Meowave — full schema, generated by supabase/build_sql.mjs
-- Paste the whole file into the Supabase SQL editor and press Run.
-- Safe to run repeatedly: every statement is idempotent.

-- ======================================================
-- migrations/01_core.sql
-- ======================================================
-- Meowave: schema + Row Level Security.
-- Запускать в Supabase SQL Editor (или supabase db push).
-- Безопасность строится на RLS-политиках, а не на секретности anon key.

-- ── profiles ────────────────────────────────────────────────
create table if not exists public.profiles (
  id         uuid primary key references auth.users (id) on delete cascade,
  username   text,
  avatar_url text,
  updated_at timestamptz not null default now()
);

alter table public.profiles enable row level security;

drop policy if exists "profiles are readable by everyone" on public.profiles;
create policy "profiles are readable by everyone"
  on public.profiles for select using (true);

drop policy if exists "users insert own profile" on public.profiles;
create policy "users insert own profile"
  on public.profiles for insert with check (auth.uid() = id);

drop policy if exists "users update own profile" on public.profiles;
create policy "users update own profile"
  on public.profiles for update using (auth.uid() = id);

-- профиль создаётся автоматически при регистрации
-- The email local part is not a valid username: it can contain '+', be shorter
-- than 3 chars, or collide with someone else's. profiles_username_shape and the
-- unique index would both reject it, and because this runs inside the signup
-- transaction a rejection failed the whole registration. Sanitise, then fall
-- back to a guaranteed-unique name and let the user pick a real one later.
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  base text;
  candidate text;
begin
  base := regexp_replace(split_part(coalesce(new.email, ''), '@', 1), '[^A-Za-z0-9_.-]', '', 'g');
  if length(base) < 3 then
    base := 'meow' || base;
  end if;
  base := left(base, 20);

  candidate := base;
  -- A handful of attempts, then give up on a pretty name rather than block signup.
  for i in 1..5 loop
    exit when not exists (select 1 from public.profiles where lower(username) = lower(candidate));
    candidate := left(base, 14) || '_' || substr(replace(new.id::text, '-', ''), 1, 5 + i);
  end loop;
  if exists (select 1 from public.profiles where lower(username) = lower(candidate)) then
    candidate := null;
  end if;

  insert into public.profiles (id, username)
  values (new.id, candidate)
  on conflict (id) do nothing;
  return new;
exception when others then
  -- Never let profile cosmetics break account creation.
  insert into public.profiles (id) values (new.id) on conflict (id) do nothing;
  return new;
end $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ── friendships ─────────────────────────────────────────────
-- Defined here rather than in 04_social because the profile visibility policy
-- in 02 and check_achievements() in 03 both reference this table, and Postgres
-- resolves table names when a policy or function body is created, not when it
-- runs. Creating it later made a from-scratch `psql -f schema.sql` fail on 02.
-- The friendship RPCs and the rest of the social layer still live in 04.
--
-- The canonical direction of a friendship is (requester, addressee): a single
-- row covers both people, so queries have to check both columns.
create table if not exists public.friendships (
  requester uuid not null references auth.users (id) on delete cascade,
  addressee uuid not null references auth.users (id) on delete cascade,
  status     text not null default 'pending'
             check (status in ('pending', 'accepted', 'blocked')),
  created_at timestamptz not null default now(),
  primary key (requester, addressee),
  constraint no_self_friendship check (requester <> addressee)
);

alter table public.friendships enable row level security;

-- Stop A->B and B->A existing at the same time: order the pair before indexing it.
create unique index if not exists friendships_pair_key
  on public.friendships (least(requester, addressee), greatest(requester, addressee));

create index if not exists friendships_addressee_idx on public.friendships (addressee, status);

-- ── playlists ───────────────────────────────────────────────
create table if not exists public.playlists (
  id         uuid primary key default gen_random_uuid(),
  owner_id   uuid not null references auth.users (id) on delete cascade,
  name       text not null,
  created_at timestamptz not null default now()
);

alter table public.playlists enable row level security;

drop policy if exists "owners manage own playlists" on public.playlists;
create policy "owners manage own playlists"
  on public.playlists for all
  using (auth.uid() = owner_id)
  with check (auth.uid() = owner_id);

-- ── playlist_tracks ─────────────────────────────────────────
create table if not exists public.playlist_tracks (
  playlist_id     uuid not null references public.playlists (id) on delete cascade,
  source          text not null,          -- spotify | ytm | sc | ym
  source_track_id text not null,
  title           text not null,
  artist          text,
  cover_url       text,
  position        int  not null default 0,
  primary key (playlist_id, source, source_track_id)
);

alter table public.playlist_tracks enable row level security;

drop policy if exists "owners manage tracks of own playlists" on public.playlist_tracks;
create policy "owners manage tracks of own playlists"
  on public.playlist_tracks for all
  using (exists (select 1 from public.playlists p
                 where p.id = playlist_id and p.owner_id = auth.uid()))
  with check (exists (select 1 from public.playlists p
                      where p.id = playlist_id and p.owner_id = auth.uid()));

-- ── storage: bucket "avatars" ───────────────────────────────
-- Публичное чтение; писать можно только в свою папку <uid>/...
insert into storage.buckets (id, name, public)
values ('avatars', 'avatars', true)
on conflict (id) do nothing;

drop policy if exists "avatar images are publicly readable" on storage.objects;
create policy "avatar images are publicly readable"
  on storage.objects for select
  using (bucket_id = 'avatars');

drop policy if exists "users upload own avatar" on storage.objects;
create policy "users upload own avatar"
  on storage.objects for insert
  with check (bucket_id = 'avatars'
              and (storage.foldername(name))[1] = auth.uid()::text);

-- An UPDATE policy needs BOTH using and with check. `upsert: true` on an
-- existing avatar is an UPDATE, and with check defaulting to the using clause
-- is not enough here: Storage rewrites metadata on overwrite, so the row is
-- re-validated against with check. Without it the second avatar upload failed
-- while the first one appeared to work.
drop policy if exists "users update own avatar" on storage.objects;
create policy "users update own avatar"
  on storage.objects for update
  using (bucket_id = 'avatars'
         and (storage.foldername(name))[1] = auth.uid()::text)
  with check (bucket_id = 'avatars'
         and (storage.foldername(name))[1] = auth.uid()::text);

drop policy if exists "users delete own avatar" on storage.objects;
create policy "users delete own avatar"
  on storage.objects for delete
  using (bucket_id = 'avatars'
         and (storage.foldername(name))[1] = auth.uid()::text);

-- ── удаление аккаунта из клиента ────────────────────────────
-- anon key не может удалять auth.users напрямую, поэтому security definer rpc:
create or replace function public.delete_account()
returns void language plpgsql security definer set search_path = public as $$
begin
  if auth.uid() is null then
    raise exception 'not authenticated';
  end if;
  delete from auth.users where id = auth.uid();
end $$;

revoke all on function public.delete_account() from public;
grant execute on function public.delete_account() to authenticated;


-- ======================================================
-- migrations/02_profile_extended.sql
-- ======================================================
-- Profile customisation: banner, colors, and the stats the leaderboard reads.
-- Run after schema.sql.

alter table public.profiles
  add column if not exists banner_url   text,
  add column if not exists bio          text,
  add column if not exists accent       text,          -- hex or accent id picked in the UI
  add column if not exists card_style   text default 'plain',
  add column if not exists pinned_badge text,          -- badge id shown next to the name
  add column if not exists is_public    boolean not null default true,
  add column if not exists created_at   timestamptz not null default now();

-- Usernames are how people find each other in rooms and friend search, so they
-- have to be unique. Case-insensitive: "Cat" and "cat" are the same person.
create unique index if not exists profiles_username_key
  on public.profiles (lower(username)) where username is not null;

-- Postgres has no "add constraint if not exists", so drop first. Without this
-- a second `psql -f schema.sql` died on "constraint already exists" — and since
-- 02 aborted, everything after it (banners, badges, favorites) silently never
-- got applied. That is why avatars and banners looked broken on a re-run.
alter table public.profiles drop constraint if exists profiles_username_shape;
alter table public.profiles
  add constraint profiles_username_shape
  check (username is null or username ~ '^[A-Za-z0-9_.-]{3,24}$') not valid;

alter table public.profiles drop constraint if exists profiles_bio_len;
alter table public.profiles
  add constraint profiles_bio_len check (bio is null or length(bio) <= 300) not valid;

-- Private profiles stay visible to the owner and to friends only. Replaces the
-- blanket "readable by everyone" policy from schema.sql.
drop policy if exists "profiles are readable by everyone" on public.profiles;

drop policy if exists "public profiles, own profile, and friends" on public.profiles;
create policy "public profiles, own profile, and friends"
  on public.profiles for select using (
    is_public
    or auth.uid() = id
    or exists (
      select 1 from public.friendships f
      where f.status = 'accepted'
        and ((f.requester = auth.uid() and f.addressee = profiles.id)
          or (f.addressee = auth.uid() and f.requester = profiles.id))
    )
  );

-- ── listening stats ─────────────────────────────────────────
-- One row per user. Counters only ever move up, which keeps the leaderboard
-- cheap: no aggregation over a play-history table on every page load.
create table if not exists public.user_stats (
  user_id        uuid primary key references auth.users (id) on delete cascade,
  listen_seconds bigint not null default 0,
  tracks_played  bigint not null default 0,
  unique_tracks  bigint not null default 0,
  spatial_seconds bigint not null default 0,
  night_sessions int    not null default 0,
  rooms_hosted   int    not null default 0,
  updated_at     timestamptz not null default now(),
  constraint stats_sane check (listen_seconds >= 0 and tracks_played >= 0)
);

alter table public.user_stats enable row level security;

drop policy if exists "stats of visible profiles are readable" on public.user_stats;
create policy "stats of visible profiles are readable"
  on public.user_stats for select using (
    exists (select 1 from public.profiles p where p.id = user_id)
  );

drop policy if exists "users write own stats" on public.user_stats;
create policy "users write own stats"
  on public.user_stats for all
  using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- Weekly buckets, so "top listener this week" doesn't need a play log either.
create table if not exists public.weekly_stats (
  user_id        uuid not null references auth.users (id) on delete cascade,
  week_start     date not null,
  listen_seconds bigint not null default 0,
  primary key (user_id, week_start)
);

alter table public.weekly_stats enable row level security;

drop policy if exists "weekly stats are readable" on public.weekly_stats;
create policy "weekly stats are readable"
  on public.weekly_stats for select using (true);

drop policy if exists "users write own weekly stats" on public.weekly_stats;
create policy "users write own weekly stats"
  on public.weekly_stats for all
  using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- The client reports elapsed seconds every so often instead of writing rows per
-- track: fewer requests, and a client that lies can only inflate its own numbers.
-- Deltas are clamped so a hacked client can't claim a year of listening at once.
create or replace function public.report_listening(
  seconds int,
  new_tracks int default 0,
  spatial int default 0,
  is_night boolean default false
) returns void language plpgsql security definer set search_path = public as $$
declare
  uid uuid := auth.uid();
  s   int  := least(greatest(coalesce(seconds, 0), 0), 3600);   -- max 1h per call
  sp  int  := least(greatest(coalesce(spatial, 0), 0), s);
  nt  int  := least(greatest(coalesce(new_tracks, 0), 0), 200);
begin
  if uid is null then
    raise exception 'not authenticated';
  end if;

  insert into public.user_stats as us (user_id, listen_seconds, tracks_played,
                                       unique_tracks, spatial_seconds, night_sessions)
  values (uid, s, nt, nt, sp, case when is_night then 1 else 0 end)
  on conflict (user_id) do update set
    listen_seconds  = us.listen_seconds + s,
    tracks_played   = us.tracks_played + nt,
    unique_tracks   = us.unique_tracks + nt,
    spatial_seconds = us.spatial_seconds + sp,
    night_sessions  = us.night_sessions + case when is_night then 1 else 0 end,
    updated_at      = now();

  insert into public.weekly_stats as ws (user_id, week_start, listen_seconds)
  values (uid, date_trunc('week', now())::date, s)
  on conflict (user_id, week_start) do update set
    listen_seconds = ws.listen_seconds + s;

  perform public.check_achievements();
end $$;

grant execute on function public.report_listening(int, int, int, boolean) to authenticated;

-- ── leaderboards ────────────────────────────────────────────
-- Views, not tables: always current, and RLS on the base tables still applies.
create or replace view public.leaderboard_alltime as
  select p.id, p.username, p.avatar_url, p.pinned_badge,
         s.listen_seconds, s.tracks_played,
         rank() over (order by s.listen_seconds desc) as rank
  from public.user_stats s
  join public.profiles p on p.id = s.user_id
  where p.is_public and s.listen_seconds > 0
  order by s.listen_seconds desc
  limit 100;

create or replace view public.leaderboard_weekly as
  select p.id, p.username, p.avatar_url, p.pinned_badge,
         w.listen_seconds,
         rank() over (order by w.listen_seconds desc) as rank
  from public.weekly_stats w
  join public.profiles p on p.id = w.user_id
  where p.is_public
    and w.week_start = date_trunc('week', now())::date
    and w.listen_seconds > 0
  order by w.listen_seconds desc
  limit 100;

-- The badges leaderboard view lives in 03_badges.sql: it joins
-- public.user_badges, which does not exist yet at this point, so defining it
-- here aborted the whole schema run on a fresh database (42P01) and nothing
-- after this line was ever applied.

-- ── storage: banners ────────────────────────────────────────
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('banners', 'banners', true, 4194304,
        array['image/jpeg','image/png','image/webp','image/gif'])
on conflict (id) do update set
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

-- Avatars accept GIF too, so animated avatars work. 2 MB is plenty once the
-- client has resized; the limit exists to stop someone parking a video here.
update storage.buckets
   set file_size_limit = 2097152,
       allowed_mime_types = array['image/jpeg','image/png','image/webp','image/gif']
 where id = 'avatars';

drop policy if exists "banners are publicly readable" on storage.objects;
create policy "banners are publicly readable"
  on storage.objects for select using (bucket_id = 'banners');

drop policy if exists "users upload own banner" on storage.objects;
create policy "users upload own banner"
  on storage.objects for insert
  with check (bucket_id = 'banners'
              and (storage.foldername(name))[1] = auth.uid()::text);

-- Same as avatars: upsert of an existing banner is an UPDATE and needs
-- with check, or only the very first upload succeeds.
drop policy if exists "users update own banner" on storage.objects;
create policy "users update own banner"
  on storage.objects for update
  using (bucket_id = 'banners'
         and (storage.foldername(name))[1] = auth.uid()::text)
  with check (bucket_id = 'banners'
         and (storage.foldername(name))[1] = auth.uid()::text);

drop policy if exists "users delete own banner" on storage.objects;
create policy "users delete own banner"
  on storage.objects for delete
  using (bucket_id = 'banners'
         and (storage.foldername(name))[1] = auth.uid()::text);


-- ======================================================
-- migrations/03_badges.sql
-- ======================================================
-- Badges: the catalog, who owns what, and the promo codes.
--
-- Storage cost was a requirement, so nothing here stores an image. `badges`
-- holds ids and thresholds; the art ships inside the app under
-- src/assets/badges/. A user owning 60 badges costs ~60 rows of ~50 bytes.

-- ── catalog ─────────────────────────────────────────────────
create table if not exists public.badges (
  id       text primary key,                 -- matches badges.json
  source   text not null check (source in ('achievement', 'code')),
  rarity   text not null default 'common'
           check (rarity in ('common','rare','epic','legendary')),
  -- Threshold for achievements, checked by check_achievements() below. Null for
  -- code badges and for anything granted by hand.
  metric   text,
  threshold bigint,
  compare  text not null default 'gte' check (compare in ('gte','lte')),
  active   boolean not null default true
);

alter table public.badges enable row level security;

drop policy if exists "badge catalog is public" on public.badges;
create policy "badge catalog is public"
  on public.badges for select using (true);
-- No insert/update policy: the catalog is seeded from SQL, not from the client.

-- ── ownership ───────────────────────────────────────────────
create table if not exists public.user_badges (
  user_id  uuid not null references auth.users (id) on delete cascade,
  badge_id text not null references public.badges (id) on delete cascade,
  earned_at timestamptz not null default now(),
  primary key (user_id, badge_id)
);

alter table public.user_badges enable row level security;

drop policy if exists "badges of visible profiles are readable" on public.user_badges;
create policy "badges of visible profiles are readable"
  on public.user_badges for select using (
    exists (select 1 from public.profiles p where p.id = user_id)
  );
-- Grants happen only through the security-definer functions below, so a client
-- can't hand itself a legendary badge.

create index if not exists user_badges_user_idx on public.user_badges (user_id);

-- ── promo codes ─────────────────────────────────────────────
-- The code itself is never stored: only sha256(upper(trim(code))). A database
-- leak doesn't leak the codes.
create table if not exists public.badge_codes (
  code_hash  text primary key,
  badge_id   text not null references public.badges (id) on delete cascade,
  max_uses   int,                            -- null = unlimited
  uses       int not null default 0,
  expires_at timestamptz,
  note       text                            -- for the maintainer, e.g. "stream giveaway"
);

alter table public.badge_codes enable row level security;
-- No select policy at all: nobody reads this table from the client, not even to
-- count rows. redeem_badge_code() runs as definer and bypasses RLS.

create or replace function public.hash_code(raw text)
returns text language sql immutable as $$
  select encode(digest(upper(btrim(raw)), 'sha256'), 'hex')
$$;

-- pgcrypto provides digest(); Supabase ships it, this just makes it explicit.
create extension if not exists pgcrypto with schema extensions;

create or replace function public.redeem_badge_code(raw_code text)
returns table (badge_id text, already_owned boolean)
language plpgsql security definer set search_path = public, extensions as $$
declare
  uid  uuid := auth.uid();
  rec  public.badge_codes;
  owned boolean;
begin
  if uid is null then
    raise exception 'not authenticated';
  end if;
  if raw_code is null or btrim(raw_code) = '' then
    raise exception 'empty code';
  end if;

  select * into rec from public.badge_codes
   where code_hash = public.hash_code(raw_code)
   for update;

  if not found then
    raise exception 'invalid code';
  end if;
  if rec.expires_at is not null and rec.expires_at < now() then
    raise exception 'code expired';
  end if;
  if rec.max_uses is not null and rec.uses >= rec.max_uses then
    raise exception 'code exhausted';
  end if;

  select exists (select 1 from public.user_badges ub
                  where ub.user_id = uid and ub.badge_id = rec.badge_id)
    into owned;

  if not owned then
    insert into public.user_badges (user_id, badge_id) values (uid, rec.badge_id);
    -- A redeem that granted nothing shouldn't burn a use of a limited code.
    update public.badge_codes set uses = uses + 1 where code_hash = rec.code_hash;
  end if;

  return query select rec.badge_id, owned;
end $$;

revoke all on function public.redeem_badge_code(text) from public;
grant execute on function public.redeem_badge_code(text) to authenticated;

-- ── automatic unlocks ───────────────────────────────────────
-- Called from report_listening() and on demand after the profile loads. Grants
-- every achievement whose threshold the caller's stats now satisfy.
create or replace function public.check_achievements()
returns setof text language plpgsql security definer set search_path = public as $$
declare
  uid uuid := auth.uid();
begin
  if uid is null then
    return;
  end if;

  return query
  with me as (
    select s.*,
           (select count(*) from public.friendships f
             where f.status = 'accepted'
               and (f.requester = uid or f.addressee = uid)) as friends,
           (select count(*) from public.user_badges ub where ub.user_id = uid) as badge_count
      from public.user_stats s where s.user_id = uid
  ),
  vals as (
    select b.id, b.compare, b.threshold,
           case b.metric
             when 'listen_seconds'   then me.listen_seconds
             when 'tracks_played'    then me.tracks_played
             when 'unique_tracks'    then me.unique_tracks
             when 'spatial_seconds'  then me.spatial_seconds
             when 'night_sessions'   then me.night_sessions::bigint
             when 'rooms_hosted'     then me.rooms_hosted::bigint
             when 'friends'          then me.friends
             when 'badges_owned'     then me.badge_count
             else null
           end as value
      from public.badges b cross join me
     where b.source = 'achievement' and b.active and b.metric is not null
  ),
  won as (
    insert into public.user_badges (user_id, badge_id)
    select uid, id from vals
     where value is not null
       and ((compare = 'gte' and value >= threshold)
         or (compare = 'lte' and value <= threshold))
    on conflict (user_id, badge_id) do nothing
    returning badge_id
  )
  select badge_id from won;
end $$;

grant execute on function public.check_achievements() to authenticated;

-- Metrics the client tracks locally (connected services, custom EQ presets)
-- can't be verified server-side, so the client reports them and the same
-- threshold check runs here rather than trusting a client-side grant.
create or replace function public.claim_client_badge(badge text, value bigint)
returns boolean language plpgsql security definer set search_path = public as $$
declare
  uid uuid := auth.uid();
  b   public.badges;
begin
  if uid is null then
    raise exception 'not authenticated';
  end if;

  select * into b from public.badges
   where id = badge and source = 'achievement' and active
     and metric in ('services_connected', 'custom_presets', 'leaderboard_best_rank');
  if not found then
    return false;
  end if;

  if not ((b.compare = 'gte' and value >= b.threshold)
       or (b.compare = 'lte' and value <= b.threshold)) then
    return false;
  end if;

  insert into public.user_badges (user_id, badge_id) values (uid, b.id)
  on conflict do nothing;
  return true;
end $$;

grant execute on function public.claim_client_badge(text, bigint) to authenticated;

-- ── seed ────────────────────────────────────────────────────
-- The catalog is NOT seeded here any more.
--
-- This file used to carry a hand-written list of 18 badges. It had drifted so
-- far from src/assets/badges/badges.json that not one id matched: the database
-- knew 18 badges that no longer exist, and none of the 36 that do. Codes then
-- failed with a foreign key violation because the badge they referenced was
-- never inserted.
--
-- badges.json is the single source of truth. Generate the insert from it:
--
--   node supabase/make_badges_sql.mjs   -> supabase/BADGES.sql
--
-- and run that after this schema (or use seed_badges.mjs with a service key).

-- Handing out a code, from the SQL editor only. badge_id must already exist in
-- public.badges or this fails with a foreign key violation (23503), so seed the
-- catalog first:
--
--   insert into public.badge_codes (code_hash, badge_id, max_uses, note)
--   values (public.hash_code('MEOW-BOYKISSER-XXXXX'), 'boykisser', 500, 'pre-release');
--
-- In practice use `node supabase/make_codes.mjs`, which writes the whole file.
-- Never commit the plaintext.

-- ── badges leaderboard ──────────────────────────────────────
-- Defined here, after user_badges exists. It used to sit in 02, where the
-- forward reference killed a fresh install mid-run.
create or replace view public.leaderboard_badges as
  select p.id, p.username, p.avatar_url, p.pinned_badge,
         count(b.badge_id) as badges,
         rank() over (order by count(b.badge_id) desc) as rank
  from public.profiles p
  join public.user_badges b on b.user_id = p.id
  where p.is_public
  group by p.id, p.username, p.avatar_url, p.pinned_badge
  order by badges desc
  limit 100;


-- ======================================================
-- migrations/04_social.sql
-- ======================================================
-- Friends, rooms, listen-together sessions, and messages.
--
-- The canonical direction of a friendship is (requester, addressee). A single
-- row covers both people; queries have to check both columns, which is why the
-- helper below exists.

-- ── friendships ─────────────────────────────────────────────
-- The table itself now lives in 01_core: policies in 02 and check_achievements()
-- in 03 reference it, and those references are resolved at creation time, so it
-- has to exist before them. Its policies and RPCs stay here.

drop policy if exists "see own friendships" on public.friendships;
create policy "see own friendships"
  on public.friendships for select
  using (auth.uid() in (requester, addressee));

drop policy if exists "send own friend requests" on public.friendships;
create policy "send own friend requests"
  on public.friendships for insert
  with check (auth.uid() = requester and status = 'pending');

-- Only the addressee accepts. Either side can block or walk away.
drop policy if exists "respond to friend requests" on public.friendships;
create policy "respond to friend requests"
  on public.friendships for update
  using (auth.uid() in (requester, addressee))
  with check (auth.uid() in (requester, addressee));

drop policy if exists "remove own friendships" on public.friendships;
create policy "remove own friendships"
  on public.friendships for delete
  using (auth.uid() in (requester, addressee));

create or replace function public.is_friend(other uuid)
returns boolean language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.friendships
     where status = 'accepted'
       and ((requester = auth.uid() and addressee = other)
         or (addressee = auth.uid() and requester = other))
  )
$$;

grant execute on function public.is_friend(uuid) to authenticated;

-- Adding by name instead of by uuid: the UI only ever shows usernames.
create or replace function public.add_friend_by_username(name text)
returns uuid language plpgsql security definer set search_path = public as $$
declare
  uid    uuid := auth.uid();
  target uuid;
begin
  if uid is null then
    raise exception 'not authenticated';
  end if;

  select id into target from public.profiles where lower(username) = lower(btrim(name));
  if target is null then
    raise exception 'no such user';
  end if;
  if target = uid then
    raise exception 'that is you';
  end if;

  -- If they already asked us, accept instead of creating a mirrored request.
  update public.friendships set status = 'accepted'
   where requester = target and addressee = uid and status = 'pending';
  if found then
    perform public.check_achievements();
    return target;
  end if;

  insert into public.friendships (requester, addressee)
  values (uid, target)
  on conflict do nothing;

  return target;
end $$;

grant execute on function public.add_friend_by_username(text) to authenticated;

-- ── rooms ───────────────────────────────────────────────────
create table if not exists public.rooms (
  id         uuid primary key default gen_random_uuid(),
  owner_id   uuid not null references auth.users (id) on delete cascade,
  name       text not null check (length(btrim(name)) between 1 and 40),
  -- Short human code people type to join, e.g. "MEOW-4F2A".
  join_code  text not null unique,
  is_private boolean not null default false,
  topic      text check (topic is null or length(topic) <= 140),
  created_at timestamptz not null default now(),
  -- What the room is playing right now. Kept on the room row rather than in a
  -- separate table so joining is one read and playback sync is one update.
  track      jsonb,
  position   double precision not null default 0,
  playing    boolean not null default false,
  updated_at timestamptz not null default now()
);

alter table public.rooms enable row level security;

create table if not exists public.room_members (
  room_id   uuid not null references public.rooms (id) on delete cascade,
  user_id   uuid not null references auth.users (id) on delete cascade,
  role      text not null default 'listener' check (role in ('owner','dj','listener')),
  joined_at timestamptz not null default now(),
  primary key (room_id, user_id)
);

alter table public.room_members enable row level security;

create index if not exists room_members_user_idx on public.room_members (user_id);

create or replace function public.in_room(r uuid)
returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.room_members
                  where room_id = r and user_id = auth.uid())
$$;

grant execute on function public.in_room(uuid) to authenticated;

create or replace function public.can_dj(r uuid)
returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.room_members
                  where room_id = r and user_id = auth.uid()
                    and role in ('owner','dj'))
$$;

grant execute on function public.can_dj(uuid) to authenticated;

drop policy if exists "public rooms and joined rooms are visible" on public.rooms;
create policy "public rooms and joined rooms are visible"
  on public.rooms for select
  using (not is_private or public.in_room(id) or owner_id = auth.uid());

drop policy if exists "users create own rooms" on public.rooms;
create policy "users create own rooms"
  on public.rooms for insert with check (auth.uid() = owner_id);

-- DJs update playback state; the owner also renames and locks the room.
drop policy if exists "djs update room playback" on public.rooms;
create policy "djs update room playback"
  on public.rooms for update
  using (public.can_dj(id) or owner_id = auth.uid())
  with check (public.can_dj(id) or owner_id = auth.uid());

drop policy if exists "owner deletes room" on public.rooms;
create policy "owner deletes room"
  on public.rooms for delete using (auth.uid() = owner_id);

drop policy if exists "members of a visible room are listed" on public.room_members;
create policy "members of a visible room are listed"
  on public.room_members for select
  using (public.in_room(room_id)
         or exists (select 1 from public.rooms r
                     where r.id = room_id and not r.is_private));

drop policy if exists "users leave rooms themselves" on public.room_members;
create policy "users leave rooms themselves"
  on public.room_members for delete
  using (auth.uid() = user_id
         or exists (select 1 from public.rooms r
                     where r.id = room_id and r.owner_id = auth.uid()));

-- Joining goes through join_room() so private rooms and the code check can't be
-- bypassed by inserting a membership row directly.
create or replace function public.create_room(name text, private boolean default false)
returns public.rooms language plpgsql security definer set search_path = public as $$
declare
  uid  uuid := auth.uid();
  code text;
  row  public.rooms;
begin
  if uid is null then
    raise exception 'not authenticated';
  end if;

  -- 4 chars from a 32-symbol alphabet, ambiguous letters removed. Retry on the
  -- rare collision rather than making the code longer.
  for i in 1..10 loop
    code := 'MEOW-' || (
      select string_agg(substr('23456789ABCDEFGHJKLMNPQRSTUVWXYZ',
                               1 + floor(random() * 32)::int, 1), '')
        from generate_series(1, 4)
    );
    exit when not exists (select 1 from public.rooms where join_code = code);
    code := null;
  end loop;
  if code is null then
    raise exception 'could not allocate a join code';
  end if;

  insert into public.rooms (owner_id, name, join_code, is_private)
  values (uid, btrim(name), code, private)
  returning * into row;

  insert into public.room_members (room_id, user_id, role)
  values (row.id, uid, 'owner');

  update public.user_stats set rooms_hosted = rooms_hosted + 1 where user_id = uid;
  perform public.check_achievements();

  return row;
end $$;

grant execute on function public.create_room(text, boolean) to authenticated;

create or replace function public.join_room(code text)
returns public.rooms language plpgsql security definer set search_path = public as $$
declare
  uid uuid := auth.uid();
  row public.rooms;
begin
  if uid is null then
    raise exception 'not authenticated';
  end if;

  select * into row from public.rooms where join_code = upper(btrim(code));
  if not found then
    raise exception 'no such room';
  end if;

  insert into public.room_members (room_id, user_id) values (row.id, uid)
  on conflict do nothing;

  return row;
end $$;

grant execute on function public.join_room(text) to authenticated;

-- ── messages ────────────────────────────────────────────────
-- Room chat and direct messages in one table: exactly one of room_id / recipient
-- is set. Realtime subscribers filter on whichever they care about.
create table if not exists public.messages (
  id        bigserial primary key,
  room_id   uuid references public.rooms (id) on delete cascade,
  sender    uuid not null references auth.users (id) on delete cascade,
  recipient uuid references auth.users (id) on delete cascade,
  body      text not null check (length(btrim(body)) between 1 and 2000),
  sent_at   timestamptz not null default now(),
  constraint one_target check (
    (room_id is not null and recipient is null)
    or (room_id is null and recipient is not null)
  )
);

alter table public.messages enable row level security;

create index if not exists messages_room_idx on public.messages (room_id, id desc);
create index if not exists messages_dm_idx on public.messages (recipient, sender, id desc);

drop policy if exists "read room chat and own dms" on public.messages;
create policy "read room chat and own dms"
  on public.messages for select using (
    (room_id is not null and public.in_room(room_id))
    or auth.uid() in (sender, recipient)
  );

-- DMs only between friends, so the inbox can't be spammed by strangers.
drop policy if exists "send to own rooms and to friends" on public.messages;
create policy "send to own rooms and to friends"
  on public.messages for insert with check (
    auth.uid() = sender and (
      (room_id is not null and public.in_room(room_id))
      or (recipient is not null and public.is_friend(recipient))
    )
  );

drop policy if exists "delete own messages" on public.messages;
create policy "delete own messages"
  on public.messages for delete using (auth.uid() = sender);

-- ── listen together (friends, no room) ──────────────────────
-- A lightweight presence row: what a user is playing right now. Friends read it
-- to follow along without creating a room.
create table if not exists public.presence (
  user_id    uuid primary key references auth.users (id) on delete cascade,
  track      jsonb,
  position   double precision not null default 0,
  playing    boolean not null default false,
  open_to_join boolean not null default false,
  updated_at timestamptz not null default now()
);

alter table public.presence enable row level security;

drop policy if exists "friends see presence" on public.presence;
create policy "friends see presence"
  on public.presence for select
  using (auth.uid() = user_id or public.is_friend(user_id));

drop policy if exists "users write own presence" on public.presence;
create policy "users write own presence"
  on public.presence for all
  using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- Realtime: the client subscribes to these instead of polling.
alter publication supabase_realtime add table public.messages;
alter publication supabase_realtime add table public.rooms;
alter publication supabase_realtime add table public.room_members;
alter publication supabase_realtime add table public.presence;


-- ======================================================
-- migrations/05_favorites.sql
-- ======================================================
-- Favorites, synced to the account.
--
-- Until now favorites lived only in the browser's localStorage, so they were
-- tied to one machine: reinstalling the app or signing in elsewhere showed an
-- empty library even though the account was the same.
--
-- A favorite is deliberately NOT a playlist row. Playlists are ordered and
-- user-named; favorites are a set keyed by (source, track id). Reusing
-- playlist_tracks would have meant inventing a magic playlist per user and
-- carrying a `position` nobody reads.
--
-- Track metadata is denormalised into this table on purpose. The services hand
-- out short-lived ids and the app must be able to render the library offline,
-- before any search request resolves. Re-fetching titles for 500 favorites at
-- boot would be 500 requests to services that rate-limit.

create table if not exists public.favorites (
  user_id         uuid not null references auth.users (id) on delete cascade,
  -- "ytm" | "sc" | "ym" | "local"
  source          text not null,
  source_track_id text not null,
  title           text not null,
  artist          text,
  album           text,
  -- Seconds. 0 when the service didn't report a duration yet.
  duration        int  not null default 0,
  cover_url       text,
  -- Local files carry a path instead of a resolvable service id. Kept so the
  -- row is still recognisable on another machine, where the file is missing:
  -- the app shows it greyed out rather than silently dropping it.
  local_path      text,
  added_at        timestamptz not null default now(),
  primary key (user_id, source, source_track_id)
);

alter table public.favorites enable row level security;

-- Favorites are private. Unlike stats and badges there is no social feature
-- reading them, so no policy exposes another user's rows.
drop policy if exists "users manage own favorites" on public.favorites;
create policy "users manage own favorites"
  on public.favorites for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create index if not exists favorites_user_added_idx
  on public.favorites (user_id, added_at desc);

-- Upserting one row per favorite would be one request per heart click. The app
-- batches instead: it sends what changed since the last flush.
--
-- `adds` is a json array of objects shaped like the table columns; `removes` is
-- a json array of [source, source_track_id] pairs. Both are optional.
create or replace function public.sync_favorites(adds jsonb default '[]', removes jsonb default '[]')
returns int language plpgsql security definer set search_path = public as $$
declare
  uid uuid := auth.uid();
  touched int := 0;
begin
  if uid is null then
    raise exception 'not authenticated';
  end if;

  -- A runaway client shouldn't be able to write an unbounded batch.
  if jsonb_array_length(coalesce(adds, '[]')) > 500
     or jsonb_array_length(coalesce(removes, '[]')) > 500 then
    raise exception 'batch too large';
  end if;

  with incoming as (
    select
      nullif(btrim(e ->> 'source'), '')          as source,
      nullif(btrim(e ->> 'source_track_id'), '') as source_track_id,
      coalesce(nullif(btrim(e ->> 'title'), ''), '—') as title,
      e ->> 'artist'    as artist,
      e ->> 'album'     as album,
      -- Clamp: a bad duration would render as a broken progress bar forever.
      least(greatest(coalesce((e ->> 'duration')::int, 0), 0), 86400) as duration,
      e ->> 'cover_url'  as cover_url,
      e ->> 'local_path' as local_path
    from jsonb_array_elements(coalesce(adds, '[]')) e
  ),
  ins as (
    insert into public.favorites
      (user_id, source, source_track_id, title, artist, album, duration, cover_url, local_path)
    select uid, source, source_track_id, title, artist, album, duration, cover_url, local_path
      from incoming
     where source is not null and source_track_id is not null
    on conflict (user_id, source, source_track_id) do update set
      -- added_at is never touched: re-syncing must not reorder the library.
      title     = excluded.title,
      artist    = excluded.artist,
      album     = excluded.album,
      duration  = greatest(public.favorites.duration, excluded.duration),
      cover_url = coalesce(excluded.cover_url, public.favorites.cover_url),
      local_path = coalesce(excluded.local_path, public.favorites.local_path)
    returning 1
  ),
  gone as (
    delete from public.favorites f
     using jsonb_array_elements(coalesce(removes, '[]')) r
     where f.user_id = uid
       and f.source = (r ->> 0)
       and f.source_track_id = (r ->> 1)
    returning 1
  )
  select (select count(*) from ins) + (select count(*) from gone) into touched;

  return touched;
end $$;

revoke all on function public.sync_favorites(jsonb, jsonb) from public;
grant execute on function public.sync_favorites(jsonb, jsonb) to authenticated;

-- unique_tracks in user_stats counts what a user has ever played. The number of
-- favorites is a different thing and the badge catalog may want it, so expose
-- it as a cheap count rather than a stored counter that can drift.
create or replace function public.favorites_count()
returns bigint language sql security definer set search_path = public as $$
  select count(*) from public.favorites where user_id = auth.uid()
$$;

grant execute on function public.favorites_count() to authenticated;


-- ======================================================
-- migrations/06_badges_v2.sql
-- ======================================================
-- Badge catalog v2: the 36-badge set (status, achievements, boykissers).
--
-- The art that shipped with the app changed to a catalog keyed on metrics the
-- server never tracked: listening_minutes, playlists_created, tracks_liked,
-- sessions_before_7am, sessions_after_1am, longest_session_minutes,
-- distinct_genres, daily_streak. check_achievements() only knew listen_seconds,
-- tracks_played, unique_tracks, spatial_seconds, night_sessions, rooms_hosted,
-- friends and badges_owned — so seven of the nine new metrics silently matched
-- nothing and those badges could never unlock.
--
-- Storage cost was a hard requirement, so the counters below are all bigint /
-- int on the single existing user_stats row (~40 bytes added per user), and
-- nothing stores a play history.

-- ── new counters ────────────────────────────────────────────
alter table public.user_stats
  -- Derived counters kept as columns rather than computed on read: the
  -- leaderboard and the badge check both read them on every sync.
  add column if not exists playlists_created  int    not null default 0,
  add column if not exists tracks_liked       int    not null default 0,
  add column if not exists sessions_before_7am int   not null default 0,
  add column if not exists sessions_after_1am int    not null default 0,
  -- Longest single uninterrupted session, in minutes.
  add column if not exists longest_session_minutes int not null default 0,
  add column if not exists distinct_genres    int    not null default 0,
  -- Consecutive days with at least one play.
  add column if not exists daily_streak       int    not null default 0,
  add column if not exists longest_streak     int    not null default 0,
  add column if not exists last_played_on     date;

-- ── catalog shape ───────────────────────────────────────────
-- 'status' badges (Owner, Admin, Developer…) are granted by a maintainer, never
-- by a code or a threshold, so they need their own source: leaving them as
-- 'code' would mean minting a code that could leak and hand out Owner.
alter table public.badges drop constraint if exists badges_source_check;
alter table public.badges
  add constraint badges_source_check
  check (source in ('achievement', 'code', 'status'));

alter table public.badges drop constraint if exists badges_rarity_check;
alter table public.badges
  add constraint badges_rarity_check
  check (rarity in ('common', 'uncommon', 'rare', 'epic', 'legendary', 'secret'));

-- ── metric-aware achievement check ──────────────────────────
-- Rewritten to read every metric the shipped catalog can reference. Unknown
-- metrics return null and are skipped rather than treated as zero, so a typo in
-- badges.json cannot hand out a badge to everyone.
create or replace function public.check_achievements()
returns table (badge_id text) language plpgsql security definer
set search_path = public as $$
declare
  uid uuid := auth.uid();
  st  public.user_stats;
  b   record;
  val bigint;
begin
  if uid is null then
    raise exception 'not authenticated';
  end if;

  insert into public.user_stats (user_id) values (uid) on conflict do nothing;
  select * into st from public.user_stats where user_id = uid;

  for b in
    select id, metric, threshold, compare
      from public.badges
     where source = 'achievement'
       and metric is not null
       and threshold is not null
       and id not in (select ub.badge_id from public.user_badges ub where ub.user_id = uid)
  loop
    val := case b.metric
      when 'listen_seconds'   then st.listen_seconds
      -- The catalog counts minutes; the counter is seconds.
      when 'listening_minutes' then st.listen_seconds / 60
      when 'tracks_played'    then st.tracks_played
      when 'unique_tracks'    then st.unique_tracks
      when 'spatial_seconds'  then st.spatial_seconds
      when 'night_sessions'   then st.night_sessions
      when 'rooms_hosted'     then st.rooms_hosted
      when 'playlists_created' then st.playlists_created
      when 'tracks_liked'     then st.tracks_liked
      when 'sessions_before_7am' then st.sessions_before_7am
      when 'sessions_after_1am'  then st.sessions_after_1am
      when 'longest_session_minutes' then st.longest_session_minutes
      when 'distinct_genres'  then st.distinct_genres
      when 'daily_streak'     then greatest(st.daily_streak, st.longest_streak)
      when 'friends' then (
        select count(*) from public.friendships f
         where f.status = 'accepted' and (f.requester = uid or f.addressee = uid))
      when 'badges_owned' then (
        select count(*) from public.user_badges ub where ub.user_id = uid)
      else null
    end;

    continue when val is null;

    if (b.compare = 'gte' and val >= b.threshold)
       or (b.compare = 'lte' and val <= b.threshold) then
      insert into public.user_badges (user_id, badge_id)
      values (uid, b.id)
      on conflict do nothing;
      badge_id := b.id;
      return next;
    end if;
  end loop;
end $$;

grant execute on function public.check_achievements() to authenticated;

-- ── richer listening report ─────────────────────────────────
-- Extended so the client can report the things only it can observe (session
-- length, local hour, genres) while the server still owns the thresholds.
create or replace function public.report_listening_v2(
  seconds int default 0,
  new_tracks int default 0,
  spatial int default 0,
  local_hour int default null,
  session_minutes int default 0,
  genres int default 0,
  liked int default 0,
  playlists int default 0
) returns void language plpgsql security definer set search_path = public as $$
declare
  uid uuid := auth.uid();
  today date := (now() at time zone 'utc')::date;
  prev date;
  cur_streak int;
begin
  if uid is null then
    raise exception 'not authenticated';
  end if;

  -- Clamp every input. These come from a client that can be patched, and an
  -- unbounded value would poison the leaderboard permanently.
  seconds := least(greatest(coalesce(seconds, 0), 0), 7200);
  new_tracks := least(greatest(coalesce(new_tracks, 0), 0), 200);
  spatial := least(greatest(coalesce(spatial, 0), 0), seconds);
  session_minutes := least(greatest(coalesce(session_minutes, 0), 0), 1440);
  genres := least(greatest(coalesce(genres, 0), 0), 200);
  liked := least(greatest(coalesce(liked, 0), 0), 100000);
  playlists := least(greatest(coalesce(playlists, 0), 0), 10000);

  insert into public.user_stats (user_id) values (uid) on conflict do nothing;

  select last_played_on, daily_streak into prev, cur_streak
    from public.user_stats where user_id = uid;

  -- Streak: same day is a no-op, yesterday extends, any older gap restarts.
  if prev is null or prev < today - 1 then
    cur_streak := 1;
  elsif prev = today - 1 then
    cur_streak := coalesce(cur_streak, 0) + 1;
  end if;

  update public.user_stats set
    listen_seconds = listen_seconds + seconds,
    tracks_played  = tracks_played + new_tracks,
    unique_tracks  = greatest(unique_tracks, unique_tracks + new_tracks),
    spatial_seconds = spatial_seconds + spatial,
    night_sessions = night_sessions
      + case when local_hour is not null and local_hour >= 2 and local_hour < 5 then 1 else 0 end,
    sessions_after_1am = sessions_after_1am
      + case when local_hour is not null and local_hour >= 1 and local_hour < 5 then 1 else 0 end,
    sessions_before_7am = sessions_before_7am
      + case when local_hour is not null and local_hour >= 4 and local_hour < 7 then 1 else 0 end,
    -- Monotonic maxima: a short session must not lower the record.
    longest_session_minutes = greatest(longest_session_minutes, session_minutes),
    distinct_genres = greatest(distinct_genres, genres),
    tracks_liked = greatest(tracks_liked, liked),
    playlists_created = greatest(playlists_created, playlists),
    daily_streak = cur_streak,
    longest_streak = greatest(longest_streak, cur_streak),
    last_played_on = today,
    updated_at = now()
  where user_id = uid;

  -- Weekly bucket for the weekly leaderboard.
  insert into public.weekly_stats (user_id, week, listen_seconds)
  values (uid, date_trunc('week', now())::date, seconds)
  on conflict (user_id, week) do update
    set listen_seconds = public.weekly_stats.listen_seconds + excluded.listen_seconds;
end $$;

revoke all on function public.report_listening_v2(int, int, int, int, int, int, int, int) from public;
grant execute on function public.report_listening_v2(int, int, int, int, int, int, int, int) to authenticated;

-- ── status badges ───────────────────────────────────────────
-- Granted only with the service role key (seed_badges.mjs --grant), which is
-- why there is no client-callable path to them at all.
create or replace function public.grant_badge(target uuid, badge text)
returns boolean language plpgsql security definer set search_path = public as $$
begin
  if not exists (select 1 from public.badges where id = badge) then
    raise exception 'unknown badge %', badge;
  end if;
  insert into public.user_badges (user_id, badge_id) values (target, badge)
  on conflict do nothing;
  return true;
end $$;

revoke all on function public.grant_badge(uuid, text) from public;
revoke all on function public.grant_badge(uuid, text) from authenticated;

-- ── pinned badges on the profile card ───────────────────────
-- A small ordered set shown next to the name, like the example in the design.
-- Stored as an array on the profile: at most 5 ids, so it costs nothing and
-- reads in the same query as the profile itself.
alter table public.profiles
  add column if not exists pinned_badges text[] not null default '{}';

create or replace function public.set_pinned_badges(ids text[])
returns text[] language plpgsql security definer set search_path = public as $$
declare
  uid uuid := auth.uid();
  cleaned text[];
begin
  if uid is null then
    raise exception 'not authenticated';
  end if;
  -- Only badges the user actually owns, capped at five, order preserved.
  select array_agg(x order by ord) into cleaned from (
    select x, ord from unnest(ids) with ordinality as u(x, ord)
     where exists (select 1 from public.user_badges ub
                    where ub.user_id = uid and ub.badge_id = u.x)
     limit 5
  ) s;
  cleaned := coalesce(cleaned, '{}');
  update public.profiles set pinned_badges = cleaned where id = uid;
  return cleaned;
end $$;

grant execute on function public.set_pinned_badges(text[]) to authenticated;


-- ======================================================
-- migrations/07_playlists_v2.sql
-- ======================================================
-- User playlists, cross-service.
--
-- 01_core already had `playlists` and `playlist_tracks`, but nothing in the app
-- ever wrote to them and the track rows carried no metadata — so a playlist
-- could not be rendered without re-querying every service, which is exactly
-- what fails offline and under rate limits. Same reasoning as favorites: the
-- display data lives on the row.

alter table public.playlists
  add column if not exists description text,
  add column if not exists cover_url   text,
  -- Public playlists are visible on a profile and in rooms.
  add column if not exists is_public   boolean not null default false,
  add column if not exists updated_at  timestamptz not null default now();

alter table public.playlists drop constraint if exists playlists_name_len;
alter table public.playlists
  add constraint playlists_name_len check (length(name) between 1 and 60) not valid;

alter table public.playlist_tracks
  add column if not exists title      text,
  add column if not exists artist     text,
  add column if not exists album      text,
  add column if not exists duration   int not null default 0,
  add column if not exists cover_url  text,
  add column if not exists local_path text,
  add column if not exists added_at   timestamptz not null default now();

-- Explicit ordering: a playlist is an ordered list, unlike favorites. Kept as a
-- sparse integer so a reorder rewrites one row instead of renumbering all.
alter table public.playlist_tracks
  add column if not exists position int not null default 0;

create index if not exists playlist_tracks_order_idx
  on public.playlist_tracks (playlist_id, position);

-- Public playlists need a read path for people who are not the owner.
drop policy if exists "public playlists are readable" on public.playlists;
create policy "public playlists are readable"
  on public.playlists for select
  using (is_public or owner_id = auth.uid());

drop policy if exists "tracks of readable playlists" on public.playlist_tracks;
create policy "tracks of readable playlists"
  on public.playlist_tracks for select
  using (exists (select 1 from public.playlists p
                  where p.id = playlist_id
                    and (p.is_public or p.owner_id = auth.uid())));

-- ── batched playlist write ──────────────────────────────────
-- One call per drag-and-drop instead of one per track.
create or replace function public.playlist_sync(
  pid uuid,
  tracks jsonb default '[]',
  replace_all boolean default true
) returns int language plpgsql security definer set search_path = public as $$
declare
  uid uuid := auth.uid();
  n int := 0;
begin
  if uid is null then
    raise exception 'not authenticated';
  end if;
  if not exists (select 1 from public.playlists where id = pid and owner_id = uid) then
    raise exception 'not your playlist';
  end if;
  if jsonb_array_length(coalesce(tracks, '[]')) > 2000 then
    raise exception 'playlist too large';
  end if;

  if replace_all then
    delete from public.playlist_tracks where playlist_id = pid;
  end if;

  insert into public.playlist_tracks
    (playlist_id, source, source_track_id, title, artist, album, duration,
     cover_url, local_path, position)
  select
    pid,
    e ->> 'source',
    e ->> 'source_track_id',
    coalesce(nullif(btrim(e ->> 'title'), ''), '—'),
    e ->> 'artist',
    e ->> 'album',
    least(greatest(coalesce((e ->> 'duration')::int, 0), 0), 86400),
    e ->> 'cover_url',
    e ->> 'local_path',
    (ord - 1) * 10
  from jsonb_array_elements(coalesce(tracks, '[]')) with ordinality as u(e, ord)
  where e ->> 'source' is not null and e ->> 'source_track_id' is not null
  on conflict (playlist_id, source, source_track_id) do update
    set position = excluded.position,
        title = excluded.title,
        artist = excluded.artist,
        duration = greatest(public.playlist_tracks.duration, excluded.duration),
        cover_url = coalesce(excluded.cover_url, public.playlist_tracks.cover_url);

  select count(*) into n from public.playlist_tracks where playlist_id = pid;

  update public.playlists set updated_at = now() where id = pid;

  -- Feeds the Playlist Creator / Playlist Master badges.
  update public.user_stats
     set playlists_created = greatest(
           playlists_created,
           (select count(*) from public.playlists where owner_id = uid))
   where user_id = uid;

  return n;
end $$;

revoke all on function public.playlist_sync(uuid, jsonb, boolean) from public;
grant execute on function public.playlist_sync(uuid, jsonb, boolean) to authenticated;

-- playlist_tracks needs the conflict target the upsert above relies on.
-- Added as a unique index rather than a primary key: 01_core may already have
-- defined a different key shape.
create unique index if not exists playlist_tracks_key
  on public.playlist_tracks (playlist_id, source, source_track_id);

create or replace function public.create_playlist(name text, public_flag boolean default false)
returns uuid language plpgsql security definer set search_path = public as $$
declare
  uid uuid := auth.uid();
  pid uuid;
begin
  if uid is null then
    raise exception 'not authenticated';
  end if;
  if (select count(*) from public.playlists where owner_id = uid) >= 200 then
    raise exception 'playlist limit reached';
  end if;
  insert into public.playlists (owner_id, name, is_public)
  values (uid, left(btrim(name), 60), public_flag)
  returning id into pid;

  update public.user_stats
     set playlists_created = greatest(
           playlists_created,
           (select count(*) from public.playlists where owner_id = uid))
   where user_id = uid;

  return pid;
end $$;

grant execute on function public.create_playlist(text, boolean) to authenticated;


-- ======================================================
-- migrations/08_artists_and_prefs.sql
-- ======================================================
-- Followed artists, saved EQ presets, and the client preferences that should
-- travel with the account.
--
-- All of it lives on the profile row rather than in new tables: these are small
-- per-user values read together with the profile, so extra tables would mean
-- extra round trips for no benefit. Storage was a stated constraint, and a
-- text[] of artist names plus a small jsonb costs a few hundred bytes.

alter table public.profiles
  -- Artist names, not ids: services disagree on artist identifiers, and the
  -- name is the only key that matches across YouTube Music, SoundCloud and
  -- local files.
  add column if not exists fav_artists text[] not null default '{}',
  -- Equaliser presets the user saved, as [{n, g:[...]}]. Kept as jsonb so
  -- adding a field later needs no migration.
  add column if not exists eq_presets  jsonb  not null default '[]',
  -- Accent colour and appearance choices, so a reinstall looks familiar.
  add column if not exists prefs       jsonb  not null default '{}';

-- Guard rails. These are client-supplied, and an unbounded array would let one
-- account bloat a row that every profile view reads.
alter table public.profiles drop constraint if exists profiles_fav_artists_len;
alter table public.profiles
  add constraint profiles_fav_artists_len
  check (array_length(fav_artists, 1) is null or array_length(fav_artists, 1) <= 500) not valid;

alter table public.profiles drop constraint if exists profiles_eq_presets_len;
alter table public.profiles
  add constraint profiles_eq_presets_len
  check (jsonb_typeof(eq_presets) = 'array' and jsonb_array_length(eq_presets) <= 50) not valid;

-- ── liked artists as a first-class action ───────────────────
-- A function rather than a direct update so the cap is enforced server-side
-- too: a patched client must not be able to write a 10k-element array.
create or replace function public.set_fav_artists(names text[])
returns text[] language plpgsql security definer set search_path = public as $$
declare
  uid uuid := auth.uid();
  cleaned text[];
begin
  if uid is null then
    raise exception 'not authenticated';
  end if;

  select array_agg(distinct btrim(x)) into cleaned
    from unnest(coalesce(names, '{}')) as u(x)
   where btrim(x) <> '' and length(btrim(x)) <= 120;

  cleaned := coalesce(cleaned, '{}');
  if array_length(cleaned, 1) > 500 then
    cleaned := cleaned[1:500];
  end if;

  update public.profiles set fav_artists = cleaned where id = uid;
  return cleaned;
end $$;

grant execute on function public.set_fav_artists(text[]) to authenticated;

-- ── saved equaliser presets ─────────────────────────────────
create or replace function public.set_eq_presets(presets jsonb)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  uid uuid := auth.uid();
begin
  if uid is null then
    raise exception 'not authenticated';
  end if;
  if jsonb_typeof(coalesce(presets, '[]')) <> 'array' then
    raise exception 'presets must be an array';
  end if;
  if jsonb_array_length(coalesce(presets, '[]')) > 50 then
    raise exception 'too many presets';
  end if;

  update public.profiles set eq_presets = coalesce(presets, '[]') where id = uid;
  return coalesce(presets, '[]');
end $$;

grant execute on function public.set_eq_presets(jsonb) to authenticated;

-- ── appearance preferences ──────────────────────────────────
-- Deliberately permissive about shape (it is the client's own settings blob)
-- but capped in size so it cannot be used as free storage.
create or replace function public.set_prefs(p jsonb)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  uid uuid := auth.uid();
begin
  if uid is null then
    raise exception 'not authenticated';
  end if;
  if length(coalesce(p, '{}')::text) > 8000 then
    raise exception 'preferences too large';
  end if;
  update public.profiles set prefs = coalesce(p, '{}') where id = uid;
  return coalesce(p, '{}');
end $$;

grant execute on function public.set_prefs(jsonb) to authenticated;

