// Mints promo codes and writes them out as a SQL file you paste into the
// Supabase SQL editor.
//
// seed_badges.mjs can already do this, but it needs SUPABASE_SERVICE_ROLE_KEY,
// which is not in .env and should not be — pasting SQL is one less secret to
// handle. Only the SHA-256 hash is stored, exactly as hash_code() computes it,
// so a leaked database still cannot reveal a working code.
//
//   node supabase/make_codes.mjs                      # one code per code badge
//   node supabase/make_codes.mjs --uses 100           # cap each at 100 uses
//   node supabase/make_codes.mjs --only owner,admin   # just these badges
//   node supabase/make_codes.mjs --prefix MEOW        # code prefix
//
// Writes:
//   supabase/CODES.sql   -> paste into SQL editor, press Run
//   supabase/CODES.txt   -> the plaintext codes, for you to hand out
//
// CODES.txt is the only place the plaintext exists. Losing it means minting new
// codes; it is git-ignored so it cannot be pushed by accident.

import { createHash, randomBytes } from "node:crypto";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const catalog = JSON.parse(
  readFileSync(join(here, "..", "src", "assets", "badges", "badges.json"), "utf8"),
);

const args = process.argv.slice(2);
const val = (f, d) => {
  const i = args.indexOf(f);
  return i >= 0 && args[i + 1] ? args[i + 1] : d;
};

const prefix = val("--prefix", "MEOW").toUpperCase().replace(/[^A-Z0-9]/g, "");
const uses = val("--uses", null);
const only = val("--only", null)?.split(",").map((s) => s.trim());
const expires = val("--expires", null);

// Status badges must never be redeemable: minting a code for Owner would let
// anyone holding it impersonate the project owner. `unlock: "status"` in the
// catalog is what marks them — it used to be an id list copied into each script,
// where one stale copy meant exactly that leak.

const hashCode = (raw) =>
  createHash("sha256").update(raw.trim().toUpperCase()).digest("hex");

// Crockford-ish alphabet: no O/0, I/1, so a code read aloud or off a stream
// overlay cannot be mistyped into a different valid code.
const ALPHABET = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
const chunk = (n) => {
  const b = randomBytes(n);
  let s = "";
  for (let i = 0; i < n; i++) s += ALPHABET[b[i] % ALPHABET.length];
  return s;
};

const targets = catalog.badges.filter(
  (b) => b.unlock === "code" && (!only || only.includes(b.id)),
);

const missingArt = targets.filter(
  (b) => !b.file || !existsSync(join(here, "..", "src", "assets", "badges", b.file)),
);
if (missingArt.length) {
  console.error(
    "Code badges reference missing art: " + missingArt.map((b) => `${b.id} -> ${b.file || "(none)"}`).join(", "),
  );
  process.exit(1);
}

if (!targets.length) {
  console.error("No matching code badges. Check --only.");
  process.exit(1);
}

const sql = [
  "-- Meowave promo codes, generated by supabase/make_codes.mjs",
  "-- Paste the whole file into the Supabase SQL editor and press Run.",
  "-- Only hashes are stored; the plaintext lives in supabase/CODES.txt.",
  "-- Re-running is safe: an existing hash keeps its current use count.",
  "",
];
const plain = [
  "Meowave promo codes — keep this file private.",
  `Generated ${new Date().toISOString()}`,
  "",
];

for (const b of targets) {
  const code = `${prefix}-${b.id.toUpperCase().replace(/_/g, "")}-${chunk(10)}`;
  sql.push(
    `insert into public.badge_codes (code_hash, badge_id, max_uses, expires_at, note)`,
    `values ('${hashCode(code)}', '${b.id}', ${uses ?? 100}, ${
      expires ? `'${expires}'` : "null"
    }, 'minted ${new Date().toISOString().slice(0, 10)}')`,
    `on conflict (code_hash) do update set`,
    `  badge_id = excluded.badge_id, max_uses = excluded.max_uses, expires_at = excluded.expires_at;`,
    "",
  );
  plain.push(`${b.name.padEnd(26)} ${code}`);
}

writeFileSync(join(here, "CODES.sql"), sql.join("\n"));
writeFileSync(join(here, "CODES.txt"), plain.join("\n") + "\n");

console.log(`${targets.length} codes minted.`);
console.log("");
console.log(plain.slice(3).join("\n"));
console.log("");
console.log("Next:");
console.log("  1. Open supabase/CODES.sql, copy everything");
console.log("  2. Supabase -> SQL Editor -> New query -> paste -> Run");
console.log("  3. Your codes are listed in supabase/CODES.txt");
