// Turns src/assets/badges/badges.json into plain SQL that seeds public.badges.
//
// seed_badges.mjs does the same over the REST API, but it needs
// SUPABASE_SERVICE_ROLE_KEY. Without a seeded catalog, badge_codes has nothing
// to reference and inserting a code fails with a foreign key violation
// (23503) — which is exactly the error the codes file produced.
//
//   node supabase/make_badges_sql.mjs
//   -> supabase/BADGES.sql   (paste into the SQL editor, press Run)
//
// Run this BEFORE CODES.sql.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const catalog = JSON.parse(
  readFileSync(join(here, "..", "src", "assets", "badges", "badges.json"), "utf8"),
);

// Status badges are granted by hand only, and that now comes from the catalog
// itself (`unlock: "status"`) rather than an id list duplicated in every script:
// a single stale copy would have let the code minter produce a redeemable Owner.
const sourceOf = (b) =>
  b.unlock === "status" ? "status" : b.unlock === "achievement" ? "achievement" : "code";

// The catalog's rarity vocabulary is wider than the original CHECK constraint;
// migration 06 widens it. Anything unexpected is clamped rather than allowed to
// abort the whole insert.
const RARITY = new Set(["common", "uncommon", "rare", "epic", "legendary", "secret"]);

const q = (v) => (v === null || v === undefined ? "null" : `'${String(v).replace(/'/g, "''")}'`);

function ruleOf(b) {
  const r = b.rule ?? {};
  if (r.gte !== undefined) return { metric: r.metric, threshold: r.gte, compare: "gte" };
  if (r.lte !== undefined) return { metric: r.metric, threshold: r.lte, compare: "lte" };
  // Code and status badges have nothing to measure.
  return { metric: null, threshold: null, compare: "gte" };
}

const rows = catalog.badges.map((b) => {
  const source = sourceOf(b);
  const rarity = RARITY.has(b.rarity) ? b.rarity : "common";
  const { metric, threshold, compare } = ruleOf(b);
  return `  (${q(b.id)}, ${q(source)}, ${q(rarity)}, ${q(metric)}, ${
    threshold ?? "null"
  }, ${q(compare)}, true)`;
});

const sql = `-- Meowave badge catalog, generated by supabase/make_badges_sql.mjs
-- Source of truth: src/assets/badges/badges.json
--
-- Run this BEFORE CODES.sql: badge_codes references badges(id), so codes for an
-- unseeded catalog fail with a foreign key violation.
--
-- Safe to re-run: existing rows are updated in place, ownership is untouched.

insert into public.badges (id, source, rarity, metric, threshold, compare, active)
values
${rows.join(",\n")}
on conflict (id) do update set
  source    = excluded.source,
  rarity    = excluded.rarity,
  metric    = excluded.metric,
  threshold = excluded.threshold,
  compare   = excluded.compare,
  active    = excluded.active;

-- Sanity check: should print the catalog size.
select source, count(*) from public.badges group by source order by source;
`;

const target = join(here, "BADGES.sql");
writeFileSync(target, sql);

const by = {};
for (const b of catalog.badges) {
  const s = sourceOf(b);
  by[s] = (by[s] || 0) + 1;
}

console.log(`Wrote ${target}`);
console.log(`${catalog.badges.length} badges:`, by);
console.log("\nNext:");
console.log("  1. Paste supabase/BADGES.sql into the SQL editor -> Run");
console.log("  2. Then paste supabase/CODES.sql -> Run");
